In [1]:
import numpy as np

In [2]:
mylist=[1,2,3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
nested_list=[[1,2],[3,4],[5,6]]

In [5]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [6]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(2)

array([0.61005485, 0.00382241])

In [22]:
np.random.rand(3,4)

array([[0.80657369, 0.83809925, 0.10471803, 0.89573008],
       [0.88091481, 0.79377109, 0.98799635, 0.25517845],
       [0.23576093, 0.43078193, 0.24287131, 0.81496318]])

In [24]:
np.random.randn(5,5)

array([[-1.83514814, -0.64298481,  0.53393586, -0.3505137 , -0.88143193],
       [-0.03977571,  1.53079594,  1.17659826,  0.1987438 , -0.39139246],
       [ 1.03544109, -0.38572688, -0.33904174, -2.89954966, -0.75459173],
       [ 0.66784089,  0.03090732,  0.91125604, -0.41369276, -0.80631424],
       [-1.57752375, -0.83078405,  0.92859891,  1.10251344,  0.33775413]])

In [28]:
np.random.randint(1,10,(2,3))

array([[6, 5, 8],
       [3, 8, 6]])

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [32]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [37]:
for i in range(8):
    print(i)

0
1
2
3
4
5
6
7


In [38]:
arr=np.arange(25)

In [43]:
ranarr=np.random.randint(0,50,10)

In [44]:
arr.shape

(25,)

In [45]:
arr.shape

(25,)

In [50]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr=arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [53]:
ranarr.max()

43

In [54]:
ranarr.argmax()

7

In [55]:
ranarr.min()

1

In [56]:
ranarr.argmin()

5

In [57]:
ranarr.dtype

dtype('int32')

In [58]:
myarr=np.random.rand(4)

In [59]:
myarr.dtype

dtype('float64')

In [60]:
print('avijit')

avijit


In [61]:
mylist=[1,2,3]

In [62]:
np.array(mylist)

array([1, 2, 3])

In [63]:
arr=np.arange(0,11)

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr[8]

8

In [66]:
arr[1:5]

array([1, 2, 3, 4])

In [67]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [68]:
arr[:5]

array([0, 1, 2, 3, 4])

In [69]:
arr[5]

5

In [70]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr[0:5]=100

In [73]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [76]:
arr=np.arange(0,11)

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
slice_of_arr=arr[0:5]

In [79]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
slice_of_arr[:]=99

In [82]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [83]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [84]:
arr_copy=arr.copy()

In [85]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [86]:
arr_copy[:]=100

In [87]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [88]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [89]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [90]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [91]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [92]:
arr_2d.shape

(3, 3)

In [93]:
arr_2d[0]

array([ 5, 10, 15])

In [95]:
arr_2d[2]

array([35, 40, 45])

In [98]:
arr_2d[2,1]

40

In [99]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [100]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [101]:
arr=np.arange(1,11)

In [102]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [106]:
bool_arr=arr>4

In [107]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [108]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [109]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])